# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_student_grade_from_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
