# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_student_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='notes',
            new_name='private_notes',
        ),
        migrations.AddField(
            model_name='parent',
            name='referred_by',
            field=models.CharField(blank=True, help_text='How you heard of Dave B’s Young Programmers: A person’s name, web search, Facebook, Meetup, etc.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthdate',
            field=models.DateField(blank=True, help_text='Used so the system always knows the student’s current age', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, help_text='This makes it more convenient for the teacher to communicate with the student, but isn’t required', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade_from_age',
            field=models.IntegerField(blank=True, help_text='This is the number to subtract from the student’s age on September 1st to find the grade (usually 5)', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(help_text='The student’s full name', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True, help_text='Background on the student, including any previous programming experience; allergies, special emergency instructions, etc.'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(blank=True, help_text='This is nice for the teacher to know, but isn’t required', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='wants_courses',
            field=models.ManyToManyField(blank=True, help_text='Select zero or more', to='app.Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='when_available',
            field=models.TextField(blank=True, help_text='Used in planning new course sections'),
        ),
    ]
