# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20160725_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSectionAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Applied'), (2, 'Accepted'), (3, 'Rejected')])),
                ('changed', models.DateTimeField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Student')),
            ],
        ),
    ]
