# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_studentsectionassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sections2',
            field=models.ManyToManyField(blank=True, related_name='ss2', through='app.StudentSectionAssignment', to='app.Section'),
        ),
    ]
