# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 03:20
from __future__ import unicode_literals

from django.db import migrations
from django.db import connection


def update(apps, schemaeditor):

    cursor = connection.cursor()
    cursor.execute("SELECT student_id, section_id FROM app_student_sections")
    rows = cursor.fetchall()
    for row in rows:
        cursor.execute('''insert into app_studentsectionassignment(id, student_id, section_id)
    values(nextval('app_studentsectionassignment_id_seq'), %d, %d);''' % row)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20160728_2018'),
    ]

    operations = [
        migrations.RunPython(update),
    ]

