# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20160728_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsectionassignment',
            name='changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsectionassignment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Applied'), (2, 'Accepted'), (3, 'Rejected')], default=2),
            preserve_default=False,
        ),
    ]
