# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 03:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20160728_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sections',
        ),
    ]
