# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_remove_student_sections'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sections2',
            new_name='sections',
        ),
    ]
