# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20160728_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sections',
            field=models.ManyToManyField(blank=True, through='app.StudentSectionAssignment', to='app.Section'),
        ),
    ]
