# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20160728_2057'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentsectionassignment',
            table='app_student_section',
        ),
    ]
