# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_newsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
